//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartinPulgarConstructions {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MartinPulgarConstructions.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string AddPhotoButtonText {
            get {
                return ResourceManager.GetString("AddPhotoButtonText", resourceCulture);
            }
        }
        
        internal static string NextButtonText {
            get {
                return ResourceManager.GetString("NextButtonText", resourceCulture);
            }
        }
        
        internal static string PageSubTitle {
            get {
                return ResourceManager.GetString("PageSubTitle", resourceCulture);
            }
        }
        
        internal static string AddPhotoSectionTitle {
            get {
                return ResourceManager.GetString("AddPhotoSectionTitle", resourceCulture);
            }
        }
        
        internal static string CommentsSectionTitle {
            get {
                return ResourceManager.GetString("CommentsSectionTitle", resourceCulture);
            }
        }
        
        internal static string DetailsSectionTitle {
            get {
                return ResourceManager.GetString("DetailsSectionTitle", resourceCulture);
            }
        }
        
        internal static string LinkEventsSectionTitle {
            get {
                return ResourceManager.GetString("LinkEventsSectionTitle", resourceCulture);
            }
        }
        
        internal static string IncludePhotosToLibrary {
            get {
                return ResourceManager.GetString("IncludePhotosToLibrary", resourceCulture);
            }
        }
        
        internal static string CommentsSectionPlaceholder {
            get {
                return ResourceManager.GetString("CommentsSectionPlaceholder", resourceCulture);
            }
        }
        
        internal static string DetailsSectionTagsPlaceholder {
            get {
                return ResourceManager.GetString("DetailsSectionTagsPlaceholder", resourceCulture);
            }
        }
        
        internal static string PostDataInvalidInput {
            get {
                return ResourceManager.GetString("PostDataInvalidInput", resourceCulture);
            }
        }
        
        internal static string PostDataSuccess {
            get {
                return ResourceManager.GetString("PostDataSuccess", resourceCulture);
            }
        }
        
        internal static string PostDataFailure {
            get {
                return ResourceManager.GetString("PostDataFailure", resourceCulture);
            }
        }
        
        internal static string PostDataException {
            get {
                return ResourceManager.GetString("PostDataException", resourceCulture);
            }
        }
    }
}
